// Generated by gencpp from file depth_maping/ImagePose.msg
// DO NOT EDIT!


#ifndef DEPTH_MAPING_MESSAGE_IMAGEPOSE_H
#define DEPTH_MAPING_MESSAGE_IMAGEPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <geometry_msgs/Pose.h>

namespace depth_maping
{
template <class ContainerAllocator>
struct ImagePose_
{
  typedef ImagePose_<ContainerAllocator> Type;

  ImagePose_()
    : header()
    , image()
    , pose()
    , tracking_success(false)  {
    }
  ImagePose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image(_alloc)
    , pose(_alloc)
    , tracking_success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _tracking_success_type;
  _tracking_success_type tracking_success;





  typedef boost::shared_ptr< ::depth_maping::ImagePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::depth_maping::ImagePose_<ContainerAllocator> const> ConstPtr;

}; // struct ImagePose_

typedef ::depth_maping::ImagePose_<std::allocator<void> > ImagePose;

typedef boost::shared_ptr< ::depth_maping::ImagePose > ImagePosePtr;
typedef boost::shared_ptr< ::depth_maping::ImagePose const> ImagePoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::depth_maping::ImagePose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::depth_maping::ImagePose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::depth_maping::ImagePose_<ContainerAllocator1> & lhs, const ::depth_maping::ImagePose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image == rhs.image &&
    lhs.pose == rhs.pose &&
    lhs.tracking_success == rhs.tracking_success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::depth_maping::ImagePose_<ContainerAllocator1> & lhs, const ::depth_maping::ImagePose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace depth_maping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::depth_maping::ImagePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::depth_maping::ImagePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depth_maping::ImagePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::depth_maping::ImagePose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depth_maping::ImagePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::depth_maping::ImagePose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::depth_maping::ImagePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c7f6f8218b81e191cb8cd626ad533fb";
  }

  static const char* value(const ::depth_maping::ImagePose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c7f6f8218b81e19ULL;
  static const uint64_t static_value2 = 0x1cb8cd626ad533fbULL;
};

template<class ContainerAllocator>
struct DataType< ::depth_maping::ImagePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "depth_maping/ImagePose";
  }

  static const char* value(const ::depth_maping::ImagePose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::depth_maping::ImagePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sensor_msgs/Image image\n"
"geometry_msgs/Pose pose\n"
"bool tracking_success\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::depth_maping::ImagePose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::depth_maping::ImagePose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image);
      stream.next(m.pose);
      stream.next(m.tracking_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImagePose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::depth_maping::ImagePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::depth_maping::ImagePose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "image: ";
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tracking_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tracking_success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEPTH_MAPING_MESSAGE_IMAGEPOSE_H
